FORMAT: 1A
HOST: http://api.bingo.boom

# BingoBoom API
Пример межпартнёрского API.
Все запросы и ответ передаются через HTTP(s) с исползованием JSON

## Авторизация
Каждое обращение должно содержать объект `auth` с 2 обязательными параметрами: `login` и `pass`.

В поле `login` вводится уникальный текстовый идентификатор партнёра.
Поле `pass` представляет собой *SHA-2 256 bit* хеш пароля.

## Поиск игрока [/search{login,pass,phone}]
Ресурс возвращающий номер кошелька, баланс и самого игрока

+ Parameters

    + login (string) ... Уникальный идентификатор партнёра
    + pass (string) ... SHA2 256 хеш пароля партнёра
    + phone (string) ... Номер телефона для поиска


+ Model (application/json)

    + Body

            {
                "nickname": "Ivan",
                "balance": "0.00",
                "phone": "79060060999",
                "wallet_id": 654644,
                "surname": "Иванов",
                "name": "Иван",
                "patronymic": "Иванович",
                "birthday": "1980-08-01",
                "document": "21",
                "docNumber": "1234567890"
            }
            
### Поиск [POST]
Возвращает игрока и его уникальный номер кошелька

Ответ содержит следующии параметры:

- `nickname` - псевдоним игрока
- `balance` - сумма денег на балансе
- `phone` - номер телефон
- `wallet_id` - уникальный номер кошелька
- `surname` - фамилия
- `name` - имя
- `patronymic` - отчество
- `birthday` - день рождения
- `document` - тип документа
- `docNumber` - серия и номер документа


---


+ Request (application/json)

    + Body

            {
                "auth": {
                    "login": "megaPeople",
                    "pass": "759725001aee57b4cbf50c83173d7e7ef36970af51b393bee2e66170af6d5101"
                },
                "phone": "79060060999"
            }

+ Response 200

    [Поиск игрока][]

+ Response 401

    + Body

            {
                "error": "Invalid login or password"
            }

+ Response 403

    + Body

            {
                "error": "Not active user"
            }

+ Response 404

    + Body

            {
                "error": "No user in DB"
            }


## Транзакции [/transactions{limit}]
Ресурс возвращающий все транзакции по переводу денег

+ Parameters

    + limit (optional, numeric) ... Количество транзакций за запрос. 0 - неограничено

+ Model (application/json)

    + Body

            {
                "transactions":[{
                    "pt_id": 1,
                    "wallet_id": 654644,
                    "amount": "10.00",
                    "destination": "send",
                    "status": "pending",
                    "created_at": "2014-08-01T23:00:49-07:00"
                    }, {
                    "pt_id": 10,
                    "wallet_id": 654645,
                    "amount": "11.00",
                    "destination": "request",
                    "status": "complete",
                    "created_at": "2013-08-01T23:00:49-07:00"}
                ]
            }
            
### Получение списка транзакций [POST]
Возвращает список транзакций

Ответ содержит массив объектов со следующими параметрами:

- `pt_id` - уникальный номер транзакции
- `wallet_id` - уникальный номер кошелька
- `amount` - сумма денег для перевода
- `destination` - направление перевода (`send`|`request`)
- `status` - текущее состояние перевода (`pending`|`complete`|`canceled`)
- `created_at` - дата и время создания


---


+ Request (application/json)
    + Body

            {
                "auth": {
                    "login": "megaPeople",
                    "pass": "7c94566cd9aba3680d19e1b000a948ffbca075fd320956b23b6a1f3a0d28ff1f"
                },
                "limit": 10
            }

+ Response 200

    [Транзакции][]
    
+ Response 401

    + Body

            {
                "error": "Invalid login or password"
            }

## Отправка денег партнёру [/transactions/send_money{wallet_id,amount}]
Перевод на игрока партнёра N суммы денег

+ Parameters

    + wallet_id (numeric) ... Уникальный номер кошелька
    + amount (numeric) ... Сумма денег для перевода

+ Model (application/json)

    + Body

            {
                "pt_id": 1,
                "wallet_id": 654644,
                "amount": "10.00",
                "destination": "send",
                "status": "pending",
                "created_at": "2014-08-01T23:00:49-07:00"
            }
            
### Отправка [POST]
Возвращает транзакцию

Ответ содержит объект со следующими параметрами:

- `pt_id` - уникальный номер транзакции
- `wallet_id` - уникальный номер кошелька
- `amount` - сумма денег для перевода
- `destination` - направление перевода
- `status` - текущее состояние перевода
- `created_at` - дата и время создания


---

+ Request (application/json)
    + Body

            {
                "auth": {
                    "login": "megaPeople",
                    "pass": "7c94566cd9aba3680d19e1b000a948ffbca075fd320956b23b6a1f3a0d28ff1f"
                },
                "wallet_id": 1234,
                "amount": "15.00"
            }

+ Response 200

    [Отправка денег партнёру][]
    
+ Response 401

    + Body

            {
                "error": "Invalid login or password"
            }
    
+ Response 402

    + Body

            {
                "error": "Not enough money"
            }
    
+ Response 403

    + Body

            {
                "error": "Not valid wallet_id"
            }


## Снятие денег из системы партнёра [/transactions/request_money{wallet_id,amount}]
Перевод на игрока из системы партнёра N суммы денег

+ Parameters

    + wallet_id (numeric) ... Уникальный номер кошелька
    + amount (numeric) ... Сумма денег для перевода

+ Model (application/json)

    + Body

            {
                "pt_id": 1,
                "wallet_id": 654644,
                "amount": "10.00",
                "destination": "request",
                "status": "pending",
                "created_at": "2014-08-01T23:00:49-07:00"
            }
            
### Отправка [POST]
Возвращает транзакцию

Ответ содержит объект со следующими параметрами:

- `pt_id` - уникальный номер транзакции
- `wallet_id` - уникальный номер кошелька
- `amount` - сумма денег для перевода
- `destination` - направление перевода
- `status` - текущее состояние перевода
- `created_at` - дата и время создания


---

+ Request (application/json)
    + Body

            {
                "auth": {
                    "login": "megaPeople",
                    "pass": "7c94566cd9aba3680d19e1b000a948ffbca075fd320956b23b6a1f3a0d28ff1f"
                },
                "wallet_id": 1234,
                "amount": "15.00"
            }

+ Response 200

    [Снятие денег из системы партнёра][]
    
+ Response 401

    + Body

            {
                "error": "Invalid login or password"
            }
    
+ Response 402

    + Body

            {
                "error": "Not enough money"
            }
    
+ Response 403

    + Body

            {
                "error": "Not valid wallet_id"
            }


