FORMAT: 1A
HOST: http://api.bingo.boom

# BingoBoom API
Пример межпартнёрского API

 
## Поиск игрока [/search]
Ресурс возвращающий номер кошелька, баланс и самого игрока

+ Model (application/hal+json)

    + Body

            {
                "active": 1,
                "nickname": "Ivan",
                "balance": "0.00",
                "phone": "79060060999",
                "wallet_id": 654644,
                "surname": "Иванов",
                "name": "Иван",
                "patronymic": "Иванович",
                "birthday": "1980-08-01"
            }
            
### Поиск [POST]
Возвращает игрока

+ Request (application/json)
    + Body

            {
                "auth": {
                    "login": "megaPeople",
                    "pass": "7c94566cd9aba3680d19e1b000a948ffbca075fd320956b23b6a1f3a0d28ff1f"
                },
                "phone": "79060060999"
            }

+ Response 200

    [Поиск игрока][]


# Folder Collection [/folder]
Get all of the Folders.

+ Model (application/hal+json)

    + Body

            {
                "folders": [
                    {
                        "wallet_id": 1,
                        "name": "Health",
                        "description": "This represents projects that are related to health"
                        "parent": 0,
                        "meta": "NULL"
                    },
                    {
                        "id": 1,
                        "name": "Diet",
                        "description": "A collection of projects related to Diet",
                        "parent": 1,
                        "meta": "NULL"
                    }
                ]
            }



## List all Folders [GET]

+ Response 200

    [Folder Collection][]