FORMAT: 1A
HOST: http://api.bingo.boom

# BingoBoom API
Пример межпартнёрского API

 
## Поиск игрока по номеру телефона [/search/phone/]
Ресурс возвращающий номер кошелька, баланс и самого игрока

### Поиск по телефону [POST]
Возвращает игрока

+ Request (application/json)
    + Body

            {
                "auth": {
                    "login": "megaPeople",
                    "pass": "7c94566cd9aba3680d19e1b000a948ffbca075fd320956b23b6a1f3a0d28ff1f"
                },
                "scopes": ["gist_write"]
            }

+ Response 200 (application/hal+json)
    + Body

            {
                "gambler": {
                    "self": { "href": "/" },
                    "gists": { "href": "/gists?{since}", "templated": true }
                }
            }


# Folder Collection [/folder]
Get all of the Folders.

+ Model (application/hal+json)

    + Body

            {
                "folders": [
                    {
                        "wallet_id": 1,
                        "name": "Health",
                        "description": "This represents projects that are related to health"
                        "parent": 0,
                        "meta": "NULL"
                    },
                    {
                        "id": 1,
                        "name": "Diet",
                        "description": "A collection of projects related to Diet",
                        "parent": 1,
                        "meta": "NULL"
                    }
                ]
            }



## List all Folders [GET]

+ Response 200

    [Folder Collection][]